<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
</head>
<body>
<script>
  /*
  * 1.Promise.prototype.then()
  *   &Promise.prototype.catch()
  *   &Promise.prototype.finally()方法默认返回的都是成功状态的Promise实例
  *
  * 2.可以在.then()
  *         &.catch()
  *         &.finally()方法中返回一个成功或者失败的Promise实例来自定义返回值的Promise实例的状态
  *
  *
  * */
  let p1 = Promise.resolve(100)
  let p2 = p1
      .then(data => console.log(data))
      .catch(err => console.log(err))
  p2
      .then(() => {
        console.log('resolved')
        return Promise.reject('失败')
      })
      .catch(err => console.log(err))
      .then(() => console.log('成功'))
      .then(() => console.log(111))
      .finally(() => console.log('finally'))
      .then(() => console.log('finally then()'))
      .catch(() => console.log('finally catch()'))
</script>
</body>
</html>
